Add browser_web spec
ooni/spec pull request #244
Opened 2022-06-02 16:26 UTC by hellais

This is a draft spec for ooni/probe-web: https://ooni.github.io/probe-web/

2022-06-07 13:21 UTC, bassosimone requested changes
Please, document the issue with Mozilla Firefox 🙏

2022-06-07 13:21 UTC, bassosimone commented on nettests/ts-036-browser_web.md
> +it will always show up as a failure, making the measurement unreliable.
Please, document the Firefox option that was making a bunch of my measurements fail as well. There should be enough information to document the issue in our Slack logs.

2022-06-07 13:21 UTC, bassosimone commented on nettests/ts-036-browser_web.md
> +API](https://developer.mozilla.org/en-US/docs/Web/API/Performance)) and if the
```suggestion
API](https://developer.mozilla.org/en-US/docs/Web/API/Performance)) and whether the
```

2022-06-24 16:43 UTC, bassosimone commented on nettests/ts-036-browser_web.md
> +Because the information collected by this test is not very detailed some extra
```suggestion
## Caveats

Because the information collected by this test is not very detailed some extra
```

2022-06-24 16:45 UTC, bassosimone commented on nettests/ts-036-browser_web.md
> +  the requested resource;
```suggestion
  the requested resource.
```

2022-06-24 16:47 UTC, bassosimone commented on nettests/ts-036-browser_web.md
> +experiment.
I am failing to understand the purpose of this sentence. Should I read it as "the implementation SHOULD detect whether the user..." or "the implementation MUST detect whether the user...". Or is it more like "we don't currently handle this problem and a future version of the experiment SHOULD handle this failure so you should be careful when analyzing the results". So, I'd invest a bit more time to clarify which case we are in (or, if it's another different case, to spell out exactly which case this is).

2022-06-24 17:45 UTC, hellais commented on nettests/ts-036-browser_web.md
> +experiment.
I did a little bit of research into this, but as far as I can tell, there isn't really a very reliable way to detect it.

The best technique I have come up with is to make a request to a large enough sample of what firefox is known to block (they use this list: https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json) and if they all fail very quickly, then we consider it to be on.
The issue is that this may lead to false positives, because if all these sites are indeed being blocked, we would like to be able to measure it, so even in this case we probably still want to allow a manual override.

To be honest I think the best thing we can do is display a message in the beginning of the test telling firefox users that if they have enabled enhanced tracking protection they should whitelist probe-web, but we don't have any guarantee that they are going to do it, so this needs to be taken into account when analysing the data.

2022-06-24 18:03 UTC, bassosimone approved these changes
🐳

2022-06-24 18:03 UTC, bassosimone commented on nettests/ts-036-browser_web.md
> +experiment.
Yeah, this strikes me as a fundamental test limitation. Thanks for explaining!

2022-06-24 18:24 UTC, merged