Write spec for OONI run
ooni/spec pull request #249
Opened 2022-06-17 13:44 UTC by aanorbel

## Description

Spec for OONI Run Service

2022-06-28 21:51 UTC, bassosimone reviewed
It's a good starting point. Please, apply the requested changes or discuss why you think they should not be implemented if you disagree with me. Thank you! 💯

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +This document aims at providing a functional specification for OONI Run.
```suggestion
This document provides a functional specification for OONI Run.
```

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +The api exposes an HTTP API allowing OONI Run web app to submit links to the
```suggestion
The ooni/api exposes an HTTP API allowing OONI Run web app to submit links to the
```

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +[about our data policy](https://ooni.io/about/data-policy/).
```suggestion
Tests submitted to the OONI Run API will be stored and processed by OONI backend
and OONI Probes the URL is shared with.
How that will happen is out of the scope of this document. You may also want to read
[about our data policy](https://ooni.io/about/data-policy/).
```

That said, I think this paragraph is not very relevant for this specification.

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +a Tor onion service as long as legacy OONI probe clients use it. The need
There are no legacy OONI Probe clients using OONI Run. So, this paragraph should probably be simplified.

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +endpoint.
Please remove this paragraph. It's about the collector.

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +be able to easily log the messages exchanged with the OONI Run Service.
Please change the wording. This wording clearly still refers to the collector.

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +When a you *create* a new OONI RUN link, the frontend sends a `POST`
```suggestion
When you *create* a new OONI RUN link, the frontend sends a `POST`
```

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +                     "urls": []
```suggestion
                     "inputs": []
```

We're already cursed enough by the fact that we think the input the experiments are URLs. Let's be more generic and allow more flexibility. It will pay off in the future.

(I know the v1 format says `urls` but this is v2 and we should make it better, so...)

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +2. MUST fail with `4xx` if the request is not compliant with its policies.
Which policies?

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +their preferred data submission format, and MUST save the OONI Run ID.
Please edit to remove unnecessary wording borrowed from the collector spec

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +Updating an OONI Run Link means appending a test to the OONI Run Link.
What about adding new URLs?

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +Upon receiving this request, the collector:
```suggestion
Upon receiving this request, the OONI Run backend:
```

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +   while the Python parser preserves them).
I don't think we need to be so strict. This wording was very careful because we were describing measurement submission but I don't think there are the same requirements here.

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +   that the measurement has been successfully submitted).
Not sure if this is needed here

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +```
I'm not sure about returning the ID here. We already know it because we just modified the OONI Run link.

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +    POST /link
```suggestion
    POST /api/v1/oonirun/link
```

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +    POST /report/${ooni_run_id}
```suggestion
    POST /api/v1/oonirun/link/${ooni_run_id}
```

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +    DELETE /link/${ooni_run_id}
```suggestion
    DELETE /api/v1/oonirun/link/${ooni_run_id}
```

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +content is implementation dependent and MAY be empty. Some existing implementations
Please mention that it should return `4xx` on failure

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +that it is emitting timestamps using UTC rather than local time.
Not sure this is relevant

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +distributed and SHOULD NOT be smaller than 15 minutes.
Not sure this is relevant

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +mandatory and reject invalid input.
Not sure this is relevant

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +                     "urls": []
```suggestion
                     "inputs": []
```

Same rationale as above

2022-06-28 21:51 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +        match the regex provided above for 'software_version'.
I am not a fan of returning this information. We used to do that in the collect for legacy reasons. I think we may also decide to avoid returning this information, actually.

2022-06-28 22:27 UTC, bassosimone commented
Forgot to mention: we should also specify how a canonical OONI Run v2 link looks like. Because we're using deep linking, I assume it could be something like `https://run.ooni.io/api/v2/nettest/ID` or `ooni://nettest/v2/ID`.

2022-07-01 09:52 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +   stale and closse it, thus preventing the server from telling the client
```suggestion
   stale and close it, thus preventing the server from telling the client
```

2022-07-05 10:51 UTC, ainghazal commented
Since conversation for this spec seems to be still open, I'll leave here a comment that I made recently to @bassosimone: if the limits in the information that can be conveyed in the url params is the limiting factor to move to a backend-based solution, we could consider encoding the information in some other way?

One obvious candidate is QRs. They're quite ubiquitous nowadays, and registering the right intent they might perhaps be able to encode a complete experiment run (we can try to pack it more efficiently; and perhaps a little research into information density of different types of QR is in order.

This is not to say not to pursue a backend (a backend with community control brings a lot of advantages), but perhaps some runs do not need of it after all.

2022-07-06 12:50 UTC, hellais commented
I like the QR code idea! However I am not sure how practical it's going to be. In practice the use-case for sharing OONI Run links is that people share them through digital means (ex. IM or social media). If you are to use a QR code image on social media, it's going to be tricky to scan the QR code from social media or IM unless you have two devices.
Unless there is some other way to go from a QR code inside of say WhatsApp to a the native phone app for handing the code.

2022-07-06 12:55 UTC, hellais commented on backends/bk-005-ooni-run.md
> +
I think we should add a list of definitions for what we mean when we talk about "OONI Run link" and "OONI Run link data".

I suggest defining the following terms:
- OONI Run link - This is the mobile deep link that when a user taps on it having the OONI Probe app installed, will trigger opening the app and be handled by it. If it's accessed from a device that doesn't have the app installed (or the handling is broken) it will display a web page prompting the user to install the app or allowing them to force opening the app with the custom scheme `ooni://`
- OONI Run descriptor - This is the metadata for an experiment run
- OONI Run descriptor URL - This is the URL used to retrieve the descriptor from a backend

2022-07-06 12:55 UTC, hellais commented on backends/bk-005-ooni-run.md
> +us or be prepared to retry without compression.
This is not relevant to this OONI Run.

2022-07-06 12:56 UTC, hellais commented on backends/bk-005-ooni-run.md
> +do not correctly set the `Content-Type`.
This is not relevant to OONI Run. There is no notion of "New" implementations since we never had a backend for OONI Run.

2022-07-06 13:43 UTC, hellais commented on backends/bk-005-ooni-run.md
> +
I think more details need to be provided on the high level architecture of how this specific system is going to work. Specifically we need to document how we go from handling an OONI Run link to retrieving the OONI Run descriptor via the OONI Run descriptor URL

2022-07-06 13:44 UTC, hellais commented on backends/bk-005-ooni-run.md
> +The same API is available via HTTP and Onion.
I don't think we should be exposing this via onion service.

2022-07-06 13:46 UTC, hellais commented on backends/bk-005-ooni-run.md
> +- you create an OONI RUN Link (see 3.1);
I think it's important here to clarify the various components you are interacting with when creating an OONI Run link and what are the bits of information that you get back when creating the link.

For example at some point you are interacting with a web service that speak to an API backend and the thing you get back is an OONI Run link that when opening with the mobile app speaks to the API backend to retrieve the OONI Run descriptor.

2022-07-06 13:47 UTC, hellais commented on backends/bk-005-ooni-run.md
> +    POST /api/v2/oonirun/link
I think this should still be nested under `/api/v1/` since the versioning is of the OONI API not the OONI Run link itself. As we don't have a `v1` OONI Run link speaking to the API we can use this without any issues.

I suggest we use as an endpoint:
```
/api/v2/oonirun/link
```

2022-10-21 13:37 UTC, hellais commented
Following a discussion I had with @ainghazal, I have updated the spec to include more details about the descriptor format.

I also factored into it the plans we had for redoing the dashboard based on the OONI Run v2 format and provided examples for how we could implement the dashboard using them.

To show how this could also work for the use-case of @ainghazal, we could imagine having an OONI Run v2 link for let's say RiseupVPN which could look like this:

```
{
"name": "RiseupVPN",
"short_description": "Run experiments related to testing RiseupVPN",
"author": "contact@ooni.org",
"nettests":
   [
      {
         "inputs": [
           "https://api.black.riseup.net:443/3/config/eip-service.json",
           "https://riseup.net/provider.json",
           "https://api.black.riseup.net:9001/json",
         ],
         "options": {
           "SkipTLSVerify": true
         },
         "test_name": "web_connectivity"
      },
      {
         "test_settings": {
            "provider": "riseupvpn"
          },
         "test_name": "openvpn"
      },
   ]
}
``` 

Where `SkipTLSVerify` should be some options understood by the OONI Probe engine to skip certificate verification (we need this since the riseup endpoints are using their own root CA) and `provider` is expected to be understood by the `check-in` API to derive the input and configuration vectors for the `openvpn` test.

We could take this approach even further and consider applying a similar treatment to all the IM tests and rebuild them using these more basic building blocks.

This does however raise the question of whether or not we would like to have an additional layer of grouping/nesting for the nettests.

For example I might want to put the RiseupVPN OONI Run link inside of the Circumvention test group, but as it's done now, I am not able to do so because the structure is too flat.

We could do this in at least two different ways.

1. We just add a tag inside of each nettest, that the apps will then know to group by
ex.
```json
{
"name": "VPN tests",
"short_description": "Run experiments related to testing VPNs",
"author": "contact@ooni.org",
"nettests":
   [
      {
         "inputs": [
           "https://api.black.riseup.net:443/3/config/eip-service.json",
           "https://riseup.net/provider.json",
           "https://api.black.riseup.net:9001/json",
         ],
         "options": {
           "SkipTLSVerify": true
         },
         "tag": "riseupvpn",
         "test_name": "web_connectivity"
      },
      {
         "test_settings": {
            "provider": "riseupvpn"
          },
         "tag": "riseupvpn",
         "test_name": "openvpn"
      },
      {
         "inputs": [
           "https://tunnebear.com/targets.json",
         ],
         "tag": "tunnelbear",
         "test_name": "web_connectivity"
      },
      {
         "test_settings": {
            "provider": "riseupvpn"
          },
         "tag": "tunnelbear",
         "test_name": "openvpn"
      },
   ]
}
```

2. We add an extra level of nesting in the nettests

1. is probably easier and it doesn't require changing the data format, but might limit our ability to enrich the tags with extra metadata (like title and description related to a certain tag).

2022-11-13 17:31 UTC, Xredmi commented
> ## Description
> Spec for OONI Run Service

2023-02-09 08:49 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +have a link to the custom prefix approach to "force" the opening of the app.
I think we should clarify the last sentence. Does it mean that the user will have a webpage with a link and the _option_ of clicking on the link to trigger the app?

2023-02-09 08:50 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +be accessible via URLs in the form:
I think it is unclear how authentication and installation would work in this case. I suggest we move this last portion of the document into its own section, named "Future work".

2023-02-09 08:53 UTC, bassosimone commented on backends/bk-005-ooni-run.md
> +* version: 2023.02.09
I removed version. We already have date and we can format dates to be version numbers, like I did. It is already burdensome to maintain one identifier, so we should not maintain two. We should migrate all specs to have their specification version number being the date of the last modification because there is no point in saying "I am implementing version 0.0.1 of oonirun v2 specification. We always implement the last version and we already factor in breaking changes by changing the name of the spec. For example, `ooni-run` and `ooni-run-v2`. In this vein, I am going to clearly name the file such that it's obvious we're referring to `ooni-run-v2`.

2023-02-09 08:54 UTC, bassosimone commented on backends/bk-005-ooni-run-v2.md
> +    "test_settings": {
This field cannot be named `test_settings` because it makes super confusing for anyone who is not super familiar with the spec to read a JSON and do not know which are options for the experiment and which are options for the backend. We should rename this field `backend_options`.

2023-02-09 08:56 UTC, bassosimone commented on backends/bk-005-ooni-run-v2.md
> +      "HTTP3Enabled": true
We have a `map[string]any` data format here. This is great. However, the base data format for experiments says that options are `[]string` instead. We need to patch the way in which we include options into the base data format to be a `map[string]any`. We should do this by adding a new field, to avoid breaking backwards compatibility (assuming we - or anyone - is parsing the options).

2023-02-09 09:02 UTC, bassosimone commented on backends/bk-005-ooni-run-v2.md
> +surprised to see it disappear from their device in the future.
We will for sure want to delete some descriptors _in some cases_. I think the text should say that we will not implement deletion as a _removal_ of the descriptor but we will allow parking a descriptor in such a way that it has no effect on the app in terms of running tests. In other words, I think that deleting the descriptor is more a social than a technical need and it should be enough to put the descriptor into a "null" state to achieve the social needs without breaking the installed applications too much.

2023-02-09 09:05 UTC, bassosimone commented on backends/bk-005-ooni-run-v2.md
> +      "category_codes": "$settings.category_codes"
I think this spec should do a better job at explaining what `$settings` is and means. I also think it may be worth considering checking whether we could reimplement the "decks" using this format: the "decks" where quite a flexible and nice format, so if we can implement the same functionality with OONI Run v2, we are definitely well positioned with this work in terms of flexibility.

2023-02-09 09:08 UTC, bassosimone commented on backends/bk-005-ooni-run-v2.md
> +restrict the character set of the `ooni_run_link_id` to just numbers. Since we
I disagree with "just" numbers. I think we should figure out a mechanism by which the real ID is just numbers but we can express the ID using `{4-digit} "-" {4-digit} ...`. I say this because, if we want to allow users to manually insert OONI Run IDs, then we need to make it simpler for that to split the digits.

2023-02-09 09:09 UTC, bassosimone requested changes
To summarize my request for changes:

- [ ] we need to rename `test_settings` to `backend_options`  because the original naming for the field allows for too much confusion between it and the `options

- [ ] we need to agree (or discuss further) the need to have a batter definition for options inside the base data format

- [ ] it is unclear how we're going to allow for CRUD operations for URLs deployed elsewhere, so we should be careful with the language and frame this as future work

- [ ] we need to specify a lightweight socially acceptable mean of deleting a OONI Run URL that perhaps does not vanish the URL but parks it forever as "gone"

- [ ] we should explain what `$settings` means in the spec and how in practice the app is going to process this kind of fields

- [ ] we should probably cross check with the old "decks" format and make sure that we can support a similar level of complexity or justify why this design is simpler (in many cases simpler is better, so I am not saying we should support all the "decks" features necessarily but that we should be asking this question)

- [ ] if adding OONI Run IDs manually is really a goal, then I suggest we figure out a way by which the link can contain numbers and dashes, to help a human to split the digits apart and avoid the risk that someone types in the wrong ID. (It may also be useful have some digits be some form of checksum for other digits, otherwise, to have more robustness).

2023-03-07 14:43 UTC, hellais commented on backends/bk-005-ooni-run-v2.md
> +      "category_codes": "$settings.category_codes"
Yes I will add a section explaining these.

2023-03-07 14:46 UTC, hellais commented on backends/bk-005-ooni-run-v2.md
> +surprised to see it disappear from their device in the future.
Added a sentence on this.

2023-03-07 14:49 UTC, hellais commented on backends/bk-005-ooni-run-v2.md
> +restrict the character set of the `ooni_run_link_id` to just numbers. Since we
Yes, I think that is a matter of presenting the input UI in a way that is conveyed, but we can still keep the link itself limited to just numbers.

I think having dashes in the links runs the risk of users not noticing that link is truncated (for example if they are clicking on it in an app which may truncate links with dashes).

There is a difference between what is the content of the link itself vs how a user might manually enter the link into the field where they can manually enter it.

An example of this is a credit card number. The number itself doesn't contain spaces, yet it's common for user interfaces to break up the number into blocks of numbers and spaces. We can do the same thing with OONI Run links.

2023-03-07 14:50 UTC, hellais commented on backends/bk-005-ooni-run-v2.md
> +restrict the character set of the `ooni_run_link_id` to just numbers. Since we
I added a sentence to further clarify that.

2023-03-07 14:52 UTC, hellais commented on backends/bk-005-ooni-run.md
> +have a link to the custom prefix approach to "force" the opening of the app.
Yes that's correct. Do you have a suggestion on how to improve the text? I added a sentence at the end saying this is how OONI Run links currently work.

2023-03-07 14:53 UTC, hellais commented on backends/bk-005-ooni-run.md
> +be accessible via URLs in the form:
Moved

2023-03-07 14:54 UTC, hellais commented on backends/bk-005-ooni-run-v2.md
> +      "HTTP3Enabled": true
Yes this makes sense. I don't think we need to edit anything in the spec though, correct?

2023-03-08 06:04 UTC, bassosimone commented on backends/bk-005-ooni-run-v2.md
> +      "HTTP3Enabled": true
correct!

2023-03-08 06:06 UTC, bassosimone approved these changes
🐳

2023-03-19 11:50 UTC, merged

2024-12-07 06:27 UTC, mScott224 approved these changes