Update OONIRun spec
ooni/spec pull request #278
Opened 2023-10-10 17:54 UTC by FedericoCeratto

Updated based on the current implementation.
https://github.com/ooni/backend/pull/678
https://github.com/ooni/backend/pull/699
https://github.com/ooni/backend/pull/702

2023-10-16 09:41 UTC, hellais commented on backends/bk-005-ooni-run-v2.md
> +"oonirun_id": "", // `string` OONI Run link identifier.
For consistency can we do a `s/oonirun_id/ooni_run_link_id` in the backend and frontend?

2023-10-16 09:42 UTC, hellais commented on backends/bk-005-ooni-run-v2.md
> -## 4.2 UPDATE an existing OONI Run link
What happened to updates for OONI Run links? I believe it is supported, so why was the update text removed?

2023-10-16 09:46 UTC, hellais commented on backends/bk-005-ooni-run-v2.md
> + - "ids": <string> // Comma-separated OONI Run link ID numbers to filter for
How are these "arguments" passed? Does this mean these are URL **parameters**? If that is the case, then we should clarify that's what we mean specify how they are passed.

2023-10-16 09:47 UTC, hellais requested changes
Some changes need to be done for clarity. The UPDATE method sections is missing. We should, for consistency, change the name of `oonirun_id` to `ooni_run_link_id` so it's consistent with what we use elsewhere.

2023-10-16 09:53 UTC, hellais commented on backends/bk-005-ooni-run-v2.md
> +"v": 1 // Response format version
Since this appears in many parts of the spec, we probably should make a table at the beginning of the doc explaining this `v` option and include a list of current version (which now starts from 1)

2023-10-16 10:04 UTC, hellais commented on backends/bk-005-ooni-run-v2.md
> +"oonirun_id": "", // `string` OONI Run link identifier.
Why are we passing the `ooni_run_link_id` as part of the create operation?

2023-10-26 10:28 UTC, FedericoCeratto commented on backends/bk-005-ooni-run-v2.md
> +"v": 1 // Response format version
Added.

2023-10-27 17:36 UTC, FedericoCeratto commented on backends/bk-005-ooni-run-v2.md
> +"oonirun_id": "", // `string` OONI Run link identifier.
When support for translations + URL updates have been added to the OONI Run links we implemented them as appending new records to the database table in order:
- to keep history of previous versions in case users want to fetch an older version instead of the latest one
- to allow incremental improvements of translations
This is implemented in https://github.com/ooni/backend/pull/699 - also see https://docs.google.com/document/d/1tsik0DZLOgYHh01RsLWWXp3ZHhHB_C07j8dcaMbGB9M/edit
On the database side rather than updating an existing OONI Run we are creating either a new version or a new translations, hence every action can be done with the `/api/_/ooni_run/create` path.
To add more items related to an already existing OONI Run link the Web UI passes `ooni_run_link_id` .
When absent the API generates a new `ooni_run_link_id` value.

2023-10-27 17:36 UTC, FedericoCeratto commented on backends/bk-005-ooni-run-v2.md
> -## 4.2 UPDATE an existing OONI Run link
See previous reply.

2023-10-27 17:36 UTC, FedericoCeratto commented on backends/bk-005-ooni-run-v2.md
> +`POST /api/_/ooni_run/create` with optional `id` argument
See previous reply.

2023-11-03 11:05 UTC, FedericoCeratto commented on backends/bk-005-ooni-run-v2.md
> + - "ids": <string> // Comma-separated OONI Run link ID numbers to filter for
They are described in https://api.ooni.io/apidocs/#/default/get_api___ooni_run_list - I'll update the PR

2024-02-23 15:06 UTC, hellais commented
This is superseeded by https://github.com/ooni/spec/pull/292

2024-02-23 15:06 UTC, closed without merging